version: '3.8'

services:

  sql_db:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - 1433:1433
    container_name: assignment1_human_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sql_db_data:/var/opt/mssql/data
    user: root

volumes:
  sql_db_data:
